#!/bin/bash

set -e # If any command fails, stop execution of the hook with that error

. hooks/proj.cfg

juju-log "Entered the $PROJ_NAME charm install hook."

apt-get update
apt-get -y --no-install-recommends install openjdk-7-jdk
apt-get -y install curl

# some common tools
mkdir /opt/tools

curl http://mirror.netcologne.de/apache.org/archiva/2.0.1/binaries/apache-archiva-2.0.1-bin.tar.gz | tar xz -C /opt/tools

juju-log "$PROJ_NAME successfully installed."
